services:
    rolland_rock_param_converter.builder.entity:
        class: RollandRock\ParamConverterBundle\Builder\EntityBuilder
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@property_accessor"
            - "@rolland_rock_param_converter.finder.request"
        public: false

    rolland_rock_param_converter.finder.request:
        class: RollandRock\ParamConverterBundle\Finder\RequestFinder
        public: false

    rolland_rock_param_converter.value_resolver.entity:
        class: RollandRock\ParamConverterBundle\ValueResolver\EntityArgumentValueResolver
        arguments:
            - "@rolland_rock_param_converter.builder.entity"
            - "@doctrine.orm.entity_manager"
            - "@rolland_rock_param_converter.finder.request"
        tags:
            - { name: controller.argument_value_resolver, priority: 110 }
